name: Tombs
main: me.externo6.tombs.Tombs
authers: externo6
version: 2.9.7
description: >
             Developed for Banxsi.com by externo6. Used for the Tomb challenges. /tombs or /tomb for all commands associated. Adds checkpoints, tomb kit and a use for the Artifact.
commands: 
  tomb:
    description: Base command for tombs.
  tombs:
    description: Base command for tombs.