name: Tombs
main: me.externo6.tombs.Tombs
authers: externo6
version: 1.2
description: >
             Developed for Banxsi.com by externo6. Used for the Tomb challenges. /tombs for all commands associated. Adds checkpoints and a use for the Artifact.
commands: 
  tombs:
    description: Base command for checkpoint.